livery = {
	{"Side_1",	DIFFUSE			,	"jf17_cpt_sp_1", false};
	{"WLT_Off",	DIFFUSE			,	"jf17_cpt_wlt_off", false};
	{"Front_HUD_1",	DIFFUSE			,	"jf17_cpt_hud_1", false};
	{"Side_3",	DIFFUSE			,	"jf17_cpt_sp_3", false};
	{"Side_4",	DIFFUSE			,	"jf17_cpt_sp_4", false};
	{"WLT_On",	DIFFUSE			,	"jf17_cpt_wlt_on", false};
	{"Adjustable_LDG",	DIFFUSE			,	"jf17_cpt_wlt_on", false};
	{"WLT_On_Adjustable",	DIFFUSE			,	"jf17_cpt_wlt_on", false};
	{"Adjustable_OXY",	DIFFUSE			,	"jf17_cpt_wlt_on", false};
	{"Adjustable_UFCP",	DIFFUSE			,	"jf17_cpt_wlt_on", false};
	{"Adjustable_AAP",	DIFFUSE			,	"jf17_cpt_wlt_on", false};
	{"Side_5",	DIFFUSE			,	"jf17_cpt_sp_5", false};
	{"Plate_Side",	DIFFUSE			,	"jf17_cpt_sp_plate", false};
	{"Pit_Frame_04",	DIFFUSE			,	"jf17_cpt_frame_04", false};
	{"Side_2",	DIFFUSE			,	"jf17_cpt_sp_2", false};
	{"Plate_Front",	DIFFUSE			,	"jf17_cpt_fp_plate", false};
	{"Front_UFCP",	DIFFUSE			,	"jf17_cpt_fp_ufcp", false};
	{"Front_MFCD",	DIFFUSE			,	"jf17_cpt_mfcd", false};
	{"Side_6",	DIFFUSE			,	"jf17_cpt_sp_6", false};
	{"Side_7",	DIFFUSE			,	"jf17_cpt_sp_7", false};
	{"Front_Clock",	DIFFUSE			,	"jf17_cpt_fp_clock", false};
	
	{"Side_1",	NORMAL_MAP			,	"jf17_cpt_sp_1_normal", true};
	{"WLT_Off",	NORMAL_MAP			,	"jf17_cpt_wlt_off_normal", true};
	{"Front_HUD_1",	NORMAL_MAP			,	"jf17_cpt_hud_1_normal", true};
	{"Side_3",	NORMAL_MAP			,	"jf17_cpt_sp_3_normal", true};
	{"Side_4",	NORMAL_MAP			,	"jf17_cpt_sp_4_normal", true};
	{"Side_5",	NORMAL_MAP			,	"jf17_cpt_sp_5_normal", true};
	{"Plate_Side",	NORMAL_MAP			,	"jf17_cpt_sp_plate_normal", true};
	{"Pit_Frame_04",	NORMAL_MAP			,	"jf17_cpt_frame_04_normal", true};
	{"Side_2",	NORMAL_MAP			,	"jf17_cpt_sp_2_normal", true};
	{"Plate_Front",	NORMAL_MAP			,	"jf17_cpt_fp_plate_normal", true};
	{"Front_UFCP",	NORMAL_MAP			,	"jf17_cpt_fp_ufcp_normal", true};
	{"Front_MFCD",	NORMAL_MAP			,	"jf17_cpt_mfcd_normal", true};
	{"Side_6",	NORMAL_MAP			,	"jf17_cpt_sp_6_normal", true};
	{"Side_7",	NORMAL_MAP			,	"jf17_cpt_sp_7_normal", true};
	{"Front_Clock",	NORMAL_MAP			,	"jf17_cpt_fp_clock_normal", true};
	{"jf17-mirror", 0, "mirrors", true};
}